FROM botfactory/docker-for-terremotibot:14.17.3
LABEL mantainer Matteo Contrini <matteo@contrini.it>
ENV REFRESHED_AT 2019-08-28

# Move to /src
WORKDIR /src

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the app files
COPY . .

# Expose ports to host
EXPOSE 5000

# Start
CMD ["npm", "run", "dev"]
