FROM public.ecr.aws/m8i2k7g9/docker-for-terremotibot:16.13.1

# Move to /src
WORKDIR /src

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the app files
COPY . .

# Expose ports to host
EXPOSE 5000

# Start
CMD ["npm", "run", "dev"]
