FROM botfactory/docker-for-terremotibot:14.17.3
LABEL mantainer Francesco Tonini <francesco@tonini.dev>
ENV REFRESHED_AT 2019-08-28
ENV NODE_ENV=production

# Move to /src
WORKDIR /src

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the app files
COPY . .

# Expose ports to host
EXPOSE 5000

# Start
CMD ["node", "/src/index.js"]
