FROM botfactory/docker-for-terremotibot:8.10.0
LABEL mantainer="Matteo Contrini <m.contrini@gmail.com>"

# Move to /src folder
WORKDIR /src

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy the app files
COPY . .

# Start
CMD ["yarn", "test"]
