services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    depends_on:
      - mongo
    volumes:
      - ./lib/config/config.json:/src/lib/config/config.json
      - ./tmp:/tmp
  mongo:
    image: mongo:4.2.2
    ports:
      - "28000:27017"
    logging:
      driver: none
