version: '3'

services:
  bot:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile.Tests
    depends_on:
      - mongo
    volumes:
      - ./test/config.json:/src/lib/config/config.json
  mongo:
    container_name: mongo
    image: mongo:4.2
    expose:
      - "27017"
    logging:
      driver: none
